version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:42"
    open-pull-requests-limit: 20
    ignore:
      - dependency-name: "io.netty:netty-bom"
      - dependency-name: "org.junit.jupiter:junit-jupiter"
      - dependency-name: "org.junit.jupiter:junit-jupiter-api"
      - dependency-name: "org.slf4j:slf4j-api"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
